language: go

go:
- 1.10.1


matrix:
  allow_failures:
  - go: tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get -u golang.org/x/lint/golint
script:
- make build
- make docker
- make test
- cd tests
- ./init.sh

- bats simple.bats
- bats drush.bats

#- go run ./cmd/gotty-client/main.go --help || true
#- make cover
#- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
